In [7]:
import pandas as pd

In [2]:
import geopandas as gpd
ports=gpd.read_file('port data/Principal_Ports/Principal_Ports.shp')
print('original projection:',ports.crs)
print('original geometry:',ports.geometry[0])
ports=ports.to_crs('EPSG:4326')
print('new projection:',ports.crs)
print('new geometry:',ports.geometry[0])
ports
 

original projection: EPSG:3857
original geometry: POINT (-8209607.61814087 5257745.82620866)
new projection: EPSG:4326
new geometry: POINT (-73.74816000000003 42.64271000000003)


FID  PORT TYPE                      PORT_NAME  RANK     TOTAL  FOREIGN_  \
0      1   505    C       Albany Port District, NY    75   4706700    736750   
1      2  3617    L                     Alpena, MI   114   2197451     35968   
2      3  2309    I     America's Central Port, IL    72   5528169         0   
3      4  4730    C                  Anacortes, WA    41  12181632   3948565   
4      5  3219    L   Ashtabula Port Authority, OH   150   1145145    479882   
..   ...   ...  ...                            ...   ...       ...       ...   
145  146  5700    C          Virginia, VA, Port of     9  69433624  64534599   
146  147  2383    C  West St. Mary Parish Port, LA    88   3604717         0   
147  148   555    C                 Wilmington, DE    54   8672852   7913566   
148  149   766    C                 Wilmington, NC    62   7019972   6493385   
149  150  2220    C                    Yabucoa, PR   148   1179876   1058794   

      EXPORTS   IMPORTS  DOMESTIC                     geometry  
0      366738    370012   3969950   POINT (-73.74816 42.64271)  
1       18739     17229   2161483   POINT (-83.42173 45.06197)  
2           0         0   5528169   POINT (-90.10405 38.84190)  
3     2491832   1456733   8233067  POINT (-122.59961 48.49594)  
4      416822     63060    665263   POINT (-80.79398 41.90369)  
..        ...       ...       ...                          ...  
145  16991280  47543319   4899025   POINT (-76.31174 36.86642)  
146         0         0   3604717   POINT (-91.51390 29.81967)  
147   7059319    854247    759286   POINT (-75.50697 39.71589)  
148   3611811   2881574    526587   POINT (-77.95050 34.22736)  
149   1058794         0    121082   POINT (-65.83623 18.05174)  

[150 rows x 11 columns]

In [3]:
import contextily as ctx
import matplotlib.pyplot as plt

#load dock data
docks_gdf = (
    #read in shape file downloaded from USACE
    gpd.read_file('port data/Dock/Dock.shp')
    #drop unneeded columns
    .drop([
        'FID', #randomly assigned table id
        'LONGITUDE', 'LATITUDE', #already coded in 'geometry' 
        'LOCATION_D', #text description of dock location
        'STREET_ADD','ZIPCODE', #street address details
        'PSA_NAME', #statistical area name, rarely used
        'COUNTY_NAM', 'COUNTY_FIP', 'CONGRESS', 'CONGRESS_F', #county and congress info
        'MILE', 'BANK', 'LATITUDE1', 'LONGITUDE1', #redundant locaation data
        'OPERATORS', 'OWNERS', #owner info
        'PURPOSE', #long-form text description of dock uses
        'DOCK', #unknown number (not unique to each row/dock)
        'HIGHWAY_NO', 'RAILWAY_NO', 'LOCATION', #redundant location info
        'COMMODITIE', 'CONSTRUCTI','MECHANICAL', 'REMARKS', 'VERTICAL_D', 
        'DEPTH_MIN', 'DEPTH_MAX','BERTHING_L', 'BERTHING_T', 'DECK_HEIGH', 
        'DECK_HEI_1', #these are rarely used stats on construction
        'SERVICE_IN','SERVICE_TE', #rarely used indicators of data entry date 
    ], axis=1)
    #set coordinate reference system to WGS84 lat/long
    .to_crs('EPSG:4326')
    #rename cols for clarity
    .rename(columns={
        'NAV_UNIT_I':'nav_unit_id',
        'NAV_UNIT_N':'nav_unit_name',
        'FACILITY_T':'facility_type',
        'CITY_OR_TO':'city',
        'STATE_POST':'state'
    })
)
#set col names to pythonic lowercase
docks_gdf.columns = docks_gdf.columns.str.lower()

In [4]:
gdf.geometry.y

NameError: name 'gdf' is not defined

In [5]:
import numpy as np
from sklearn.neighbors import KDTree
np.random.seed(0)
X = np.random.random((5, 2))  # 5 points in 2 dimensions
tree = KDTree(X)
nearest_dist, nearest_ind = tree.query(X, k=2)  # k=2 nearest neighbors where k1 = identity
print(X)
print(nearest_dist[:, 1])    # drop id; assumes sorted -> see args!
print(nearest_ind[:, 1])     # drop id 

[[0.5488135  0.71518937]
 [0.60276338 0.54488318]
 [0.4236548  0.64589411]
 [0.43758721 0.891773  ]
 [0.96366276 0.38344152]]
[0.14306129 0.1786471  0.14306129 0.20869372 0.39536284]
[2 0 0 0 1]


In [9]:
pd.DataFrame(X)

0         1
0  0.548814  0.715189
1  0.602763  0.544883
2  0.423655  0.645894
3  0.437587  0.891773
4  0.963663  0.383442

In [10]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})

# Set column 'B' to None where column 'A' is equal to 2
df.loc[df['A'] == 2, 'B'] = None

print(df)

   A    B
0  1  4.0
1  2  NaN
2  3  6.0
